version: '2'
services:
    employeeservice-app:
        image: employeeservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://employeeservice-mysql:3306/employeeservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    employeeservice-mysql:
        extends:
            file: mysql.yml
            service: employeeservice-mysql
